### ISSUE TITLE
Issue with editing addressbook contact

### ISSUE THREAD

**Issue by yl-coder** [HubTurbo/addressbook#104]
Example scenario to reproduce the error.

1) I started off with no contact
2) Created an contact
3) Try to edit some info the contact
4) this show up
![image](https://cloud.githubusercontent.com/assets/9070608/15387653/d1f5c5dc-1de0-11e6-90fe-62f5a8e12631.png)

**Comment by YijinL** [comment]
It broke from this commit: [[8] Pending local changes](https://github.com/HubTurbo/addressbook/commit/89b773d51c8091d0fff0957522c9595d9b0c8726).

Cause: the update-person method in `ModelManager` checks that edits will not cause a duplicate by these steps:
1. If both the new and old data items are `equal`, then the update will not cause a duplicate
2. If the new data is not `contained` in the current model, then the update will not cause a duplicate
3. If both conditions are not fulfilled, throw some duplicate exception

The issue is that the change in [8] replaced some `Person`s in the model with a subclass `ModelPerson`, and it **overrides** the `equals` method used in steps 1 and 2 above. 

Then the update method is fed a `Person` as the input data and a `ModelPerson` as the to-be-updated item, and fails step 1, so it will always throw a duplicate.

**Comment by YijinL** [comment]
I'll hotfix this, but the implementation will change a lot over the coming week anyway
