### ISSUE TITLE
'Delete' feature is broken

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#16]
Seems to be caused by #10

**Comment by ndt93** [comment]
This is due to the sync process overriding manual changes. Before or while a `Person` is being edited, `SyncManager` queues new data events in the `EventBus` with an old copy of the mirror data, after the editing is completed, those events are handled and immediately override the new changes.

At the moment, increasing the interval or disabling the sync process can decrease or eliminate the chance that this occurs.
