### ISSUE TITLE
Enable assertions in the production release

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#231]
As per title

**Comment by damithc** [comment]
@m133225 can you look into this?

**Comment by YijinL** [comment]
If it's too hard to do, we can always write a utility assert function (`throws AssertionError`) to replace all `assert X : Y` statements

**Comment by damithc** [comment]
That may be our last resort. We do that in TEAMMATES because app engine does not support assertions. If gradle can build the jar with assertions enabled, then we should use that.

**Comment by m133225** [comment]
Actually, it seems like this can be done by simply adding `-ea` to the launch command in `Installer`.

Experimented with dependencies like [Capsule](https://github.com/danthegoodman/gradle-capsule-plugin) (still unable to figure out the correct way to use it with our installer x.x), but seems like it will not be needed.

**Comment by damithc** [comment]
It's great if it can be done by adding `-ea` to the installer :+1:

**Comment by HansNewbie** [comment]
@m133225 actually that `-ea` in `Installer` will not fix this issue. `Installer` will be discarded after the application has been unloaded, so the next time the application is opened, it won't be through `Installer` but directly to `MainApp`.

We really need to enable assertion through gradle build (I tried searching about it to no avail). Maybe we really need `throws AssertionError`.

Another solution is changed the way `Installer` works so that it will never get removed and the app will always be launched from there. But that also means the app will take about 5MB more of the disk space.

**Comment by damithc** [comment]
I'm not sure it can be enabled through gradle. It's a runtime flag, not a compiletime flag. 5Mb extra space may be ok. 
Is it possible to have another class that launches the main app using a command (just like installer is doing now)?

**Comment by HansNewbie** [comment]
Will think about how to approach this best.
