### ISSUE TITLE
Communication between remote and model

### ISSUE THREAD

**Issue by YijinL** [HubTurbo/addressbook#340]
#### Sync down (auto)
- An event is raised by REMOTE and captured by MODEL
- The event contains the changes in the remote since the last request

**Problems for discussion**

1. Last-synced timestamp should be stored in MODEL (need to save to disk) so the sync-down scheduling thread must be able to retrieve the last-synced time from MODEL. My suggestion is for the REMOTE component's constructor to take in a `Supplier<LocalDateTime>` which will be called by the sync-thread every cycle.
- Do we keep a single last-synced time for the entire addressbook/model? Or a last synced time for every data item?
- Need to decide on data format; eg. will remote also tell model what has been deleted?

#### Sync-up (user commands)
There are two types of remote requests here:

1. Right before sending the real change request to the remote, we will query the remote to check whether there has been a change since the last-synced timing before the user starts the edit/add/del.
- The real change request to the remote:
    - add a person
    - delete one person
    - edit one persons

**Proposal:**

- MODEL was raise an event containing a `CompletableFuture`. Once REMOTE captures the event, it will `CompletableFuture.complete` with the result, and MODEL will be informed since it was waiting using `Future.get`. Any changes to propose?
- We need to decide on the visible response format. Here is the current idea: both request types will involve a `CompletableFuture<Optional<ReadOnlyPerson>>`. MODEL will get the `Optional<ReadOnlyPerson>` from the future. 
    - An empty optional means there were no changes (request type 1), or the request has failed (request type 2).
    - A filled optional contains the updated person data (request type 1), or the newly created person on the remote (ADD), the deleted person (DEL), or the person after the successful edit (EDIT)

**Comment by YijinL** [comment]
@m133225 @damithc @yl-coder @HansNewbie comments

**Comment by m133225** [comment]
Sync Down:
1. I think the thread (or the `RemoteManager`) should keep track of its own last-sync time. At least for the current implementation, letting the model know of this information brings no benefit (`RemoteManager` manages the requests to reduce API usage as much as possible). The last-sync time could be included in the returned remote response for the model to save to file.
Upon next initialization of the app, this info could be passed to the `RemoteManager` again for continuation.

2. For now, we only keep last-synced time for `Person`s since we can get updated persons since a certain time. Keeping it for `Tag`s seems redundant. Also, do we need to maintain the last-sync time? The `CloudPerson` data coming from the remote will also have a last-updated time (for each data item), which we can use as a reference.

3.
a. When a person is "deleted", it simply changes the person's `isDeleted` flag to true (just like `GitHub` issues). This counts as an update and will be returned as a person (with deleted flag) when requesting for updates.

b. When ANY tag is updated, the latest full list of tags will be returned. The model will have to resolve and see whether a tag has been deleted after the get-update response is returned.

Sync Down
1. This is not currently handled. And will probably not be ready by this release. For now, remote will assume there will be no changes since the last request.
However, if we were to handle this in the future, what should the response be if there is a remote update (for example, when trying to update a person from local)?
2. -

Proposal
(1) - Will need to refactor the current implementation in the PR. Does this also mean that `SyncManager` does not have to create its own threads for each request? Instead, it might be better for model to call methods of `SyncManager` directly and obtain a `Future<T>` instead, leaving the threading part to `SyncManager`.
(2) - Don't think the remote/sync should know of `ReadOnlyPerson` but just `Person`. It should be up to the model to convert them between each other.
  - Seems weird that the response for delete is `Optional<Person>`? I think a simple `CompletableFuture<Boolean>` will do for delete requests

**Comment by YijinL** [comment]
Syncdown
1. I agree

2. The returned cloud-sync time will be the last-updated, yes. For our model/storage, let's just maintain last-synced on the addressbook level.

3.
a. Our current `ReadOnlyPerson` interface does not have an isDeleted field, how will MODEL be able to recognise which ones are deleted?
b. okay

Sync Down
1. Ok, we will decide after the release.

Proposal

(1) - This will couple modelmanager to syncmanager, is it acceptable? It becomes blurry when to use events and when to use direct references.

(2) - Remote shouldn't know about `Person` because it's an implementation class and contains stuff like UI properties/observablelists; irrelevant for syncing. On the other hand, `ReadOnlyPerson` represents the contract for the types of readable values the "Person" domain object should have. Also `ReadOnlyPerson` is extended by `Person`
  - That means you need separate events for delete probably

**Comment by m133225** [comment]
- Okay, didn't realise `Person` is the sub-class. Either way, `RemoteService` has to know of `Person` in order to construct such an object from `CloudPerson`, but will pass only via `ReadOnlyPerson` to `RemoteManager` and `SyncManager`.

- I think we have to introduce an `isDeleted` field for the model. Either that or we could just ignore the deletion property for now.

- I think we need to have a separate event for each different request anyway (assuming that we still use events for requests)

**Comment by YijinL** [comment]
- perhaps for now you could manually split the deleted Persons and the add/updated Persons in the `syncdownevent`

**Comment by damithc** [comment]
Sorry, I didn't notice this discussion earlier. no comments to add - you two go ahead and workout something that works. 
Note that it is fine if the SyncManager wants to save stuff to hard disk at start/stop/periodically. Storage component is able to service any other component.

**Comment by HansNewbie** [comment]
No comments.

**Comment by m133225** [comment]
@YijinL Merged the PR already. Should be able to provide the model basic requests. However, haven't considered deleted persons. Maybe you can work on linking up create/update requests first?

**Comment by YijinL** [comment]
@m133225 saw your merge commit, from what i can see the response object is now a `CompletableFuture<Person>`, and when MODEL calls `Future.get()` it will return the result Person and throw the `SyncErrorException` if the sync failed?

**Comment by m133225** [comment]
Yes that is the case. However, if I'm not wrong, it will be converted into an `ExecutionException` instead.

**Comment by YijinL** [comment]
K I will just catch and print that
