### ISSUE TITLE
Single file download for the app

### ISSUE THREAD

**Issue by damithc** [HubTurbo/addressbook#378]
At the moment, new users have to download 2 jar files (am I correct?).
Ideally, it should be a single file.

**Comment by HansNewbie** [comment]
No. User only need to download 1 file, `addressbook.jar`. The `resource-<Version>.jar` file is there for auto-update, i.e. only for hosting the file. If we want to, we can host it elsewhere.

**Comment by damithc** [comment]
Can we rename that file to make it clearer that it is not meant to be downloaded?

**Comment by damithc** [comment]
e.g. `meta-{version}` (without `.jar`)

**Comment by HansNewbie** [comment]
Will think about it. If we are adding libraries, the release will contain more than the two JARs, e.g. if we add a library `logger.jar`, that `logger.jar` must be put in the release as well, hence now it will list `addressbook.jar`, `resource.jar` and `logger.jar`.

May need to tweak the updater to allow so. Should be feasible.

Would `[internal]-<library-name>.jar` be better? e.g. `[internal]-resource-V1.1.0.jar`, `[internal]-logger.jar`, etc.

**Comment by damithc** [comment]
Is it possible to zip all those jars into one zip file and the updater to unzip it after downloading? Having many files in the release is a bit untidy.

**Comment by HansNewbie** [comment]
It's possible. Will try to change updater to suit so.

**Comment by HansNewbie** [comment]
The problem with this is JxBrowser. If there is an update to JxBrowser, I cannot zip all of them together otherwise the zip file will be very big. At the same time, I cannot create platform zips automatically because there is no way to know the platform that a JAR runs on unless just check presence of certain keywords.

I can think of 3 solutions to this:
- hardcode the link to download JxBrowser to the Installer (which will download JxBrowser), but that means the JxBrowser will never be updated.
- whoever creates a release must zip files manually.
- create a hybrid system where there will be a zip without the platform dependent items and separate the platform dependent items. But we go back to the problem that the release page will have multiple JARs.

**Comment by HansNewbie** [comment]
If you want to, what I can do is this:
Will output zip to each platform separately. What happens with installer is it will download this whole zip file on the first run (instead of unpacking JARs from itself and download jxBrowser afterwards).

The downside would be user need to wait twice, that is, on downloading the installer and downloading the zip file upon opening the installer. However, with this, the installer will be the launcher as well to enable assertion in production.

**Comment by damithc** [comment]
We can have this mechanism.
1. If platform specific files are small, package all of them in one `meta-common` file. 
2. If platform specific files are big (e.g. jxbrowser) and there is an update to them, we can optionally have meta-win meta-osx etc.
That way, most releases have only one meta file and in rare cases we will have 1+platformCount files.

**Comment by HansNewbie** [comment]
Okay. Will try to do it.
